// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// feast_interval_dense
Rcpp::List feast_interval_dense(Rcpp::NumericMatrix A, double emin, double emax, int m0);
RcppExport SEXP _rafeast535_feast_interval_dense(SEXP ASEXP, SEXP eminSEXP, SEXP emaxSEXP, SEXP m0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type emin(eminSEXP);
    Rcpp::traits::input_parameter< double >::type emax(emaxSEXP);
    Rcpp::traits::input_parameter< int >::type m0(m0SEXP);
    rcpp_result_gen = Rcpp::wrap(feast_interval_dense(A, emin, emax, m0));
    return rcpp_result_gen;
END_RCPP
}
// feast_sparse
List feast_sparse(S4 A, int m0, double emin, double emax, Nullable<NumericMatrix> q0, int Nc, int max_iter);
RcppExport SEXP _rafeast535_feast_sparse(SEXP ASEXP, SEXP m0SEXP, SEXP eminSEXP, SEXP emaxSEXP, SEXP q0SEXP, SEXP NcSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< double >::type emin(eminSEXP);
    Rcpp::traits::input_parameter< double >::type emax(emaxSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type q0(q0SEXP);
    Rcpp::traits::input_parameter< int >::type Nc(NcSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(feast_sparse(A, m0, emin, emax, q0, Nc, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// rafeast_dense_cpp
Rcpp::List rafeast_dense_cpp(Rcpp::NumericMatrix A_r, double lambda_min, double lambda_max, int m0, int Nc, int max_iter);
RcppExport SEXP _rafeast535_rafeast_dense_cpp(SEXP A_rSEXP, SEXP lambda_minSEXP, SEXP lambda_maxSEXP, SEXP m0SEXP, SEXP NcSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A_r(A_rSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_min(lambda_minSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< int >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< int >::type Nc(NcSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(rafeast_dense_cpp(A_r, lambda_min, lambda_max, m0, Nc, max_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rafeast535_feast_interval_dense", (DL_FUNC) &_rafeast535_feast_interval_dense, 4},
    {"_rafeast535_feast_sparse", (DL_FUNC) &_rafeast535_feast_sparse, 7},
    {"_rafeast535_rafeast_dense_cpp", (DL_FUNC) &_rafeast535_rafeast_dense_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_rafeast535(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
