# Generated by using Rcpp::compileAttributes()
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

feast_interval_dense <- function(A, emin, emax, m0) {
    .Call(`_rafeast535_feast_interval_dense`, A, emin, emax, m0)
}

feast_sparse <- function(A, m0, emin, emax, q0 = NULL, Nc = 8L, max_iter = 20L) {
    .Call(`_rafeast535_feast_sparse`, A, m0, emin, emax, q0, Nc, max_iter)
}

rafeast_dense_cpp <- function(A_r, lambda_min, lambda_max, m0, Nc, max_iter) {
    .Call(`_rafeast535_rafeast_dense_cpp`, A_r, lambda_min, lambda_max, m0, Nc, max_iter)
}

